# Generated by Django 5.0.6 on 2024-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(default='default owner', max_length=50),
            preserve_default=False,
        ),
    ]
